### ISSUE TITLE
Uploading and imputing data

### ISSUE THREAD

**Issue by stefvanbuuren** [amices/webmice#29]
In `readme/readme.Rmd` section:  

##### **`/long`**: Impute data using the token (not yet working)

we have 

```{r}
paste0('{"data":', token, ',"maxit":2,"m":1,"seed":1}')) 
```

This should be

```{r}
paste0('{"data":"', token, '","maxit":2,"m":1,"seed":1}')) 
```

It now works if `token` is a name of an internal dataset. We get a new error 500 (internal server error) when `token` is a file in `data_uploads`.

**Comment by chStaiger** [comment]
There is currently some conflicts in how the upload and the data access paths are built. In one of the merges the shell variable `WEBMICE_LOC` was changed to `MICEROCKER_DATA_UPLOADS`. But this was never properly propagated through the code and the documentation.
If you now do 
```
export MICEROCKER_DATA_UPLOADS="<YOUR PATH>"
```
The server will try to load the data but will fail with a real Error state:
{"success":[false],"error":["Failure: reading file, not an example dataset or file on server"]}.

Will be fixed ASAP.

**Comment by chStaiger** [comment]
Should be fixed. By accident I unfortunately directly pushed to main :(.
@stefvanbuuren can you please check?
